import { LocalAttachmentStore } from "../../../packages/attachments/src/index.ts";
import { createPostgresRepository,type DatabaseRepository,type InvoiceDetail } from "../../../packages/database/src/index.ts";
import { BaseRpcAddressWatcher,TronGridAddressWatcher,type Invoice } from "../../../packages/payments/src/index.ts";
import { queueJobId,processQueueJob,notificationText,resolveWatcherAssignments,type QueueJob,type WatchInvoice } from "./core.ts";

export interface WorkerRuntimeConfig {redisUrl:string;databaseUrl:string;dataEncryptionKey:string;attachmentRoot:string;telegramBotToken?:string;telegramAdminChatId?:string;dashboardUrl:string;baseRpcUrl?:string;baseChainId?:number;tronApiBaseUrl?:string;tronApiKey?:string;paymentConfirmationsBase?:number;paymentConfirmationsTron?:number;paymentIntervalMs?:number;retentionIntervalMs?:number}
async function sendTelegramMessage(token:string,chatId:string,text:string){const response=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,disable_web_page_preview:true})});if(!response.ok)throw new Error(`TELEGRAM_NOTIFICATION_FAILED_${response.status}`)}
function asWatchInvoice(invoice:InvoiceDetail):WatchInvoice{return{id:invoice.id,network:invoice.network,token:invoice.token,recipient:invoice.recipientAddress,tokenContract:invoice.tokenContract,amountMinor:BigInt(invoice.amountMinor),decimals:invoice.decimals,createdAt:new Date(invoice.createdAt).getTime(),expiresAt:new Date(invoice.expiresAt).getTime(),status:"OPEN"}}
async function notify(config:WorkerRuntimeConfig,text:string){if(config.telegramBotToken&&config.telegramAdminChatId)await sendTelegramMessage(config.telegramBotToken,config.telegramAdminChatId,text)}
async function runQueuedNotifications(repository:DatabaseRepository,config:WorkerRuntimeConfig){if(!config.telegramBotToken)return;for(const notification of await repository.listDueNotifications(100)){const payload=notification.payload;const raw=typeof payload.text==="string"?payload.text:notificationText({kind:notification.kind,dashboardUrl:typeof payload.dashboardUrl==="string"?payload.dashboardUrl:config.dashboardUrl,summary:typeof payload.summary==="string"?payload.summary:"Open the Dev Desk for details.",...(notification.leadId?{leadId:notification.leadId}:{}),...(notification.jobId?{jobId:notification.jobId}:{})});const text=raw.replace(/[<>]/g,"").slice(0,3500);try{await sendTelegramMessage(config.telegramBotToken,notification.recipientChatId,text);await repository.markNotificationSent(notification.id)}catch(error){const message=error instanceof Error?error.message:"TELEGRAM_NOTIFICATION_FAILED";const backoffMinutes=Math.min(60,2**Math.min(6,notification.attempts));await repository.markNotificationFailed(notification.id,message,new Date(Date.now()+backoffMinutes*60_000))}}}
async function runPaymentWatch(repository:DatabaseRepository,config:WorkerRuntimeConfig){await repository.expireOpenInvoices();const open=await repository.listOpenInvoices(200);const groups=new Map<string,InvoiceDetail[]>();for(const invoice of open){const key=[invoice.network,invoice.recipientAddress,invoice.tokenContract].join("|");groups.set(key,[...(groups.get(key)??[]),invoice])}
  for(const invoices of groups.values()){const first=invoices[0]!;const min=Math.min(...invoices.map(invoice=>new Date(invoice.createdAt).getTime()));const max=Math.max(...invoices.map(invoice=>new Date(invoice.expiresAt).getTime()));let transfers;let confirmations;let actor;
    try{if(first.network==="BASE_USDC"){if(!config.baseRpcUrl)continue;actor="watcher:base-rpc";confirmations=config.paymentConfirmationsBase??12;transfers=await new BaseRpcAddressWatcher({rpcUrl:config.baseRpcUrl,chainId:config.baseChainId??8453}).listTransfers({recipient:first.recipientAddress,tokenContract:first.tokenContract,since:min,until:max})}else{actor="watcher:trongrid";confirmations=config.paymentConfirmationsTron??20;transfers=await new TronGridAddressWatcher({apiBaseUrl:config.tronApiBaseUrl??"https://api.trongrid.io",...(config.tronApiKey?{apiKey:config.tronApiKey}:{})}).listTransfers({recipient:first.recipientAddress,tokenContract:first.tokenContract,since:min,until:max})}
      const resolution=resolveWatcherAssignments(invoices.map(asWatchInvoice),transfers,confirmations);for(const [invoiceId,hashes] of resolution.ambiguous){await repository.markInvoiceAmbiguous(invoiceId,hashes,actor);await notify(config,`Payment ambiguous\nInvoice ${invoiceId}\nManual review required. No payment was assigned.`)}for(const match of resolution.confirmed){const result=await repository.confirmPayment({invoiceId:match.invoiceId,transfer:match.transfer,minConfirmations:confirmations,actor});await notify(config,notificationText({kind:"Payment confirmed",jobId:result.jobId,dashboardUrl:config.dashboardUrl,summary:`Invoice ${match.invoiceId} was matched by the read-only ${actor} watcher.`}))}
    }catch(error){console.error(JSON.stringify({level:"error",service:"worker",event:"payment-watch-group-failed",network:first.network,error:error instanceof Error?error.message:"UNKNOWN"}))}
  }
}
async function runRetention(repository:DatabaseRepository,config:WorkerRuntimeConfig){const store=new LocalAttachmentStore(config.attachmentRoot);for(const attachment of await repository.listExpiredAttachments(200)){await store.deleteStorageKey(attachment.storageKey);await repository.deleteAttachmentRecord(attachment.id,"retention-worker")}await repository.deleteExpiredDemandSignals()}
async function runDeadlineReminders(repository:DatabaseRepository,config:WorkerRuntimeConfig){if(!config.telegramBotToken||!config.telegramAdminChatId)return;for(const job of await repository.listDueDeadlineReminders(100)){await sendTelegramMessage(config.telegramBotToken,config.telegramAdminChatId,notificationText({kind:"Deadline approaching",jobId:job.jobId,dashboardUrl:config.dashboardUrl,summary:`Deadline ${job.deadline}. Review scope, access, tests, and client communication.`}));await repository.markDeadlineReminded(job.jobId)}}
export async function startBullMqRuntime(config:WorkerRuntimeConfig){const[{Queue,Worker},IORedisModule]=await Promise.all([import("bullmq") as any,import("ioredis") as any]);const IORedis=IORedisModule.default??IORedisModule;const connection=new IORedis(config.redisUrl,{maxRetriesPerRequest:null,enableReadyCheck:true});const queue=new Queue("jawad-engine",{connection,defaultJobOptions:{attempts:5,backoff:{type:"exponential",delay:5_000},removeOnComplete:500,removeOnFail:1_000}});const repository=await createPostgresRepository(config.databaseUrl,config.dataEncryptionKey);
  const worker=new Worker("jawad-engine",async(raw:any)=>{const job:QueueJob={id:String(raw.id),type:raw.name,payload:raw.data??{},attempts:raw.attemptsMade??0};if(job.type==="NOTIFY"){if((job.payload as {mode?:string}).mode==="database")await runQueuedNotifications(repository,config);else{if(!config.telegramBotToken||!config.telegramAdminChatId)throw new Error("TELEGRAM_ADMIN_NOTIFICATION_NOT_CONFIGURED");const payload=job.payload as{kind?:string;leadId?:string;jobId?:string;summary?:string};await sendTelegramMessage(config.telegramBotToken,config.telegramAdminChatId,notificationText({kind:payload.kind??"Dev Desk notification",dashboardUrl:config.dashboardUrl,summary:payload.summary??"Open the dashboard for details.",...(payload.leadId?{leadId:payload.leadId}:{}),...(payload.jobId?{jobId:payload.jobId}:{})}))}}else if(job.type==="PAYMENT_WATCH")await runPaymentWatch(repository,config);else if(job.type==="RETENTION_DELETE")await runRetention(repository,config);else if(job.type==="DEADLINE_REMINDER")await runDeadlineReminders(repository,config);return processQueueJob(job)},{connection,concurrency:4,limiter:{max:20,duration:1_000}});
  worker.on("failed",(job:any,error:Error)=>console.error(JSON.stringify({level:"error",service:"worker",jobId:job?.id,jobType:job?.name,error:error.message})));worker.on("completed",(job:any)=>console.log(JSON.stringify({level:"info",service:"worker",event:"completed",jobId:job.id,jobType:job.name})));
  const enqueuePayment=()=>queue.add("PAYMENT_WATCH",{mode:"read_only"},{jobId:queueJobId("PAYMENT_WATCH","configured-wallets",new Date().toISOString().slice(0,16))});const enqueueRetention=()=>queue.add("RETENTION_DELETE",{policy:"configured"},{jobId:queueJobId("RETENTION_DELETE","expired-records",new Date().toISOString().slice(0,10))});const enqueueNotifications=()=>queue.add("NOTIFY",{mode:"database"},{jobId:queueJobId("NOTIFY","database-queue",new Date().toISOString().slice(0,16))});const enqueueDeadlines=()=>queue.add("DEADLINE_REMINDER",{window:"24h"},{jobId:queueJobId("DEADLINE_REMINDER","active-jobs",new Date().toISOString().slice(0,13))});void enqueuePayment();void enqueueRetention();void enqueueNotifications();void enqueueDeadlines();const paymentInterval=setInterval(()=>void enqueuePayment(),config.paymentIntervalMs??60_000);const retentionInterval=setInterval(()=>void enqueueRetention(),config.retentionIntervalMs??24*60*60_000);const notificationInterval=setInterval(()=>void enqueueNotifications(),30_000);const deadlineInterval=setInterval(()=>void enqueueDeadlines(),60*60_000);
  return{queue,worker,async close(){clearInterval(paymentInterval);clearInterval(retentionInterval);clearInterval(notificationInterval);clearInterval(deadlineInterval);await worker.close();await queue.close();await repository.close();await connection.quit()}};
}
