import { NextResponse } from "next/server";
import { createPostgresRepository } from "@jawad/database";
import { sameOrigin,verifyAdminSession,verifyCsrfToken } from "@jawad/security";
function cookie(request:Request,name:string){return request.headers.get("cookie")?.match(new RegExp(`(?:^|; )${name}=([^;]+)`))?.[1]}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!sameOrigin(request.url,request.headers.get("origin")))return NextResponse.json({error:"ORIGIN_REJECTED"},{status:403});const secret=process.env.ADMIN_SESSION_SECRET??"";const sessionToken=cookie(request,"jawad_admin_session");const session=verifyAdminSession(sessionToken,secret);const form=await request.formData();const cookieCsrf=cookie(request,"jawad_csrf");const csrf=String(form.get("csrf")??"");if(!session||session.role!=="owner"||!cookieCsrf||csrf!==cookieCsrf||!verifyCsrfToken(sessionToken??"",csrf,secret))return NextResponse.json({error:"AUTH_REJECTED"},{status:403});
  const network=String(form.get("network")??"") as "TRON_TRC20"|"BASE_USDC";if(!["TRON_TRC20","BASE_USDC"].includes(network))return NextResponse.json({error:"INVALID_NETWORK"},{status:422});const recipient=network==="TRON_TRC20"?process.env.USDT_TRC20_RECEIVING_ADDRESS:process.env.USDC_BASE_RECEIVING_ADDRESS;const tokenContract=network==="TRON_TRC20"?process.env.USDT_TRC20_TOKEN_CONTRACT:process.env.USDC_BASE_TOKEN_CONTRACT;if(!recipient||!tokenContract)return NextResponse.json({error:"PAYMENT_NETWORK_NOT_CONFIGURED"},{status:503});
  const {id}=await params;const leadId=String(form.get("leadId")??"");if((process.env.DEMO_MODE??"true")==="true")return NextResponse.redirect(new URL(`/admin/leads/${leadId}`,request.url),303);if(!process.env.DATABASE_URL||!process.env.DATA_ENCRYPTION_KEY)return NextResponse.json({error:"DATABASE_NOT_CONFIGURED"},{status:503});const repo=await createPostgresRepository(process.env.DATABASE_URL,process.env.DATA_ENCRYPTION_KEY);
  try{const invoiceId=await repo.createInvoiceForQuote({quoteId:id,network,recipientAddress:recipient,tokenContract,decimals:6,expiresAt:new Date(Date.now()+30*60_000),actor:session.subject});const target=await repo.getLeadTelegramTarget(leadId);if(target)await repo.queueNotification({kind:"Crypto invoice ready",recipientChatId:target.telegramUserId,leadId,payload:{text:`A capacity-checked crypto invoice is ready for ticket ${target.ticketId}. Invoice ${invoiceId}. Open the Mini App, verify the token, network, amount, recipient, and expiry, then submit only the transaction hash. Never send a seed phrase or private key.`}});return NextResponse.redirect(new URL(`/admin/leads/${leadId}`,request.url),303)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"INVOICE_FAILED"},{status:409})}finally{await repo.close()}
}
