import { basename } from "node:path";
import { NextResponse } from "next/server";
import { LocalAttachmentStore } from "@jawad/attachments";
import { isDemoMode } from "@jawad/config";
import { createPostgresRepository } from "@jawad/database";
import { telegramClient } from "../../../lib/telegram-client";
import { allowRequest } from "../../../lib/rate-limit";
export const runtime="nodejs";
export async function POST(request:Request){
  const client=telegramClient(request);if(!client)return NextResponse.json({error:"INVALID_TELEGRAM_IDENTITY"},{status:401});const limit=await allowRequest("attachment",client.id);if(!limit.allowed)return NextResponse.json({error:"RATE_LIMITED",retryAfterMs:limit.retryAfterMs},{status:429});const max=Number(process.env.ATTACHMENT_MAX_BYTES??10*1024*1024);const length=Number(request.headers.get("content-length")??0);if(!isDemoMode()&&(!Number.isSafeInteger(length)||length<=0))return NextResponse.json({error:"CONTENT_LENGTH_REQUIRED"},{status:411});if(length>max+64_000)return NextResponse.json({error:"ATTACHMENT_TOO_LARGE"},{status:413});
  const form=await request.formData();const leadId=String(form.get("leadId")??"").trim();const upload=form.get("file");if(!leadId||!(upload instanceof File))return NextResponse.json({error:"LEAD_AND_FILE_REQUIRED"},{status:422});if(upload.size>max)return NextResponse.json({error:"ATTACHMENT_TOO_LARGE"},{status:413});
  if(!isDemoMode()){if(!process.env.DATABASE_URL||!process.env.DATA_ENCRYPTION_KEY)return NextResponse.json({error:"DATABASE_NOT_CONFIGURED"},{status:503});const authRepo=await createPostgresRepository(process.env.DATABASE_URL,process.env.DATA_ENCRYPTION_KEY);try{if(!await authRepo.getClientTicket(leadId,client.id))return NextResponse.json({error:"TICKET_NOT_FOUND"},{status:404})}finally{await authRepo.close()}}
  const store=new LocalAttachmentStore(process.env.ATTACHMENT_ROOT??"./runtime/uploads");let record;try{record=await store.save({name:upload.name,mime:upload.type||"application/octet-stream",bytes:Buffer.from(await upload.arrayBuffer()),retentionDays:Number(process.env.DATA_RETENTION_DAYS??30)});let attachmentId=record.id;if(!isDemoMode()){const repo=await createPostgresRepository(process.env.DATABASE_URL!,process.env.DATA_ENCRYPTION_KEY!);try{attachmentId=await repo.recordLeadAttachment({leadId,storageKey:basename(record.storagePath),originalName:upload.name,safeName:record.safeName,mime:record.mime,sizeBytes:record.size,sha256:record.sha256,scanStatus:record.scanStatus,deleteAfter:new Date(record.deleteAfter)})}catch(error){await store.delete(record).catch(()=>undefined);throw error}finally{await repo.close()}}return NextResponse.json({id:attachmentId,safeName:record.safeName,size:record.size,scanStatus:record.scanStatus,deleteAfter:new Date(record.deleteAfter).toISOString(),preview:record.redactedPreview??null},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"ATTACHMENT_REJECTED"},{status:422})}
}
