import { NextResponse } from "next/server";
import { createPostgresRepository } from "@jawad/database";
import { telegramClient } from "../../../../lib/telegram-client";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
  const client=telegramClient(request);if(!client)return NextResponse.json({error:"INVALID_TELEGRAM_IDENTITY"},{status:401});const {id}=await params;
  if(process.env.NODE_ENV!=="production"&&(process.env.DEMO_MODE??"true")==="true"){
    const base={id,status:"awaiting_review",createdAt:new Date().toISOString(),conversation:[{id:"demo-conversation",direction:"system",body:"Synthetic demo ticket created. No real client or payment data is used.",createdAt:new Date().toISOString()}],quote:{id:"demo-quote",scope:"Repair the reproducible checkout defect",acceptanceTest:["Test order is created once"],priceMinor:"100000000",currency:"USDC",network:"BASE_USDC",deliveryWindow:"Within one working day after safe access",exclusions:["Redesign"],includedWork:["Repair the bounded checkout defect","Run the agreed acceptance test"],refundTerms:"Manual review only; no automatic outgoing crypto transfer.",expiresAt:new Date(Date.now()+86400000).toISOString()}};
    if(id==="demo-paid-job")return NextResponse.json({...base,status:"awaiting_client_acceptance",invoice:{id:"demo-invoice",quoteId:"demo-quote",status:"paid",network:"BASE_USDC",token:"USDC",recipientAddress:"DEMO_NOT_PAYABLE",tokenContract:"DEMO_NOT_PAYABLE",amountMinor:"100000000",decimals:6,expiresAt:new Date(Date.now()+86400000).toISOString(),createdAt:new Date().toISOString(),txHash:"0x"+"1".repeat(64),paidAt:new Date().toISOString()},job:{id:"demo-job",status:"awaiting_client_acceptance",scope:"Repair the reproducible checkout defect",acceptanceTest:["Test order is created once"],accessChecklist:["Synthetic staging only"],proof:[],testResults:["Unit tests pass","Synthetic E2E passes"],deliveryMessage:"The synthetic checkout defect is repaired and verified in the safe demo.",createdAt:new Date().toISOString(),attachments:[{id:"demo-proof",jobId:"demo-job",safeName:"demo-proof.txt",originalName:"demo-proof.txt",mime:"text/plain",sizeBytes:26,sha256:"demo",scanStatus:"clean",deleteAfter:new Date(Date.now()+86400000).toISOString(),createdAt:new Date().toISOString()}]}});
    return NextResponse.json(base);
  }
  if(!process.env.DATABASE_URL||!process.env.DATA_ENCRYPTION_KEY)return NextResponse.json({error:"DATABASE_NOT_CONFIGURED"},{status:503});const repo=await createPostgresRepository(process.env.DATABASE_URL,process.env.DATA_ENCRYPTION_KEY);try{const ticket=await repo.getClientTicket(id,client.id);return ticket?NextResponse.json(ticket):NextResponse.json({error:"TICKET_NOT_FOUND"},{status:404})}finally{await repo.close()}
}
