import { redirect } from "next/navigation";
import { currentAdmin, loadOperations } from "../../../lib/admin";
import { demandCategoryDefinitions } from "@jawad/telegram";
export const dynamic="force-dynamic";
export default async function SettingsPage(){
  const admin=await currentAdmin();if(!admin)redirect("/admin/login");const operations=await loadOperations();const capacity=operations.capacity;
  return <main className="admin-shell"><a href="/admin">← Dashboard</a><header className="admin-top"><div><span>OPERATIONS CONTROL</span><h1>Capacity & authorised groups</h1><p>Source: {operations.source}. Monitoring remains disabled unless explicit administrator authorisation is recorded.</p></div></header>{operations.error?<div className="alert">Degraded mode: {operations.error}</div>:null}
  <section className="detail-grid"><form className="panel" method="post" action="/api/admin/settings/capacity"><h2>Capacity</h2><input type="hidden" name="csrf" value={admin.csrf}/><label>Maximum active quick fixes<input type="number" name="maximumActiveQuickFixes" min="0" max="20" defaultValue={capacity.maximumActiveQuickFixes}/></label><label>Maximum rescue jobs<input type="number" name="maximumRescueJobs" min="0" max="20" defaultValue={capacity.maximumRescueJobs}/></label><label>Next available date<input type="date" name="nextAvailableDate" defaultValue={capacity.nextAvailableDate??""}/></label><label>Working hours JSON<textarea name="workingHours" defaultValue={JSON.stringify(capacity.workingHours,null,2)}/></label><label className="check"><input type="checkbox" name="pauseCheckout" defaultChecked={capacity.pauseCheckout}/>Pause invoice checkout</label><label className="check"><input type="checkbox" name="awayMode" defaultChecked={capacity.awayMode}/>Away mode</label><button>Save audited capacity</button></form>
  <form className="panel" method="post" action="/api/admin/settings/groups"><h2>Add or update authorised group</h2><input type="hidden" name="csrf" value={admin.csrf}/><label>Telegram group ID<input name="groupId" required pattern="-?[0-9]+" placeholder="-1001234567890"/></label><label>Group title<input name="title" required maxLength={200}/></label><label>Minimum signal score<input type="number" name="minimumScore" min="1" max="30" defaultValue="6"/></label><fieldset><legend>Enabled demand categories</legend>{Object.entries(demandCategoryDefinitions).map(([id,definition])=><label className="check" key={id}><input type="checkbox" name="keywordCategories" value={id} defaultChecked/>{definition.label}</label>)}</fieldset><label className="check"><input type="checkbox" name="quietHoursEnabled"/>Suppress alerts during quiet hours</label><div className="detail-grid"><label>Quiet start hour<input type="number" name="quietStartHour" min="0" max="23" defaultValue="22"/></label><label>Quiet end hour<input type="number" name="quietEndHour" min="0" max="23" defaultValue="8"/></label></div><label>UTC offset in minutes<input type="number" name="utcOffsetMinutes" min="-720" max="840" step="15" defaultValue="180"/><small>Lebanon summer time is normally +180 minutes; verify seasonally.</small></label><label>Retention days<input type="number" name="retentionDays" min="1" max="365" defaultValue="30"/></label><label>Response mode<select name="responseMode"><option value="notify_only">Notify Jawad only</option><option value="approved_template">Pre-approved template mode</option></select></label><label>Approved response template<textarea name="approvedTemplate" maxLength={1000} placeholder="Required only for approved-template mode. Keep it factual and non-intrusive."/></label><label className="check"><input type="checkbox" name="adminAuthorised" required/>I have explicit group owner/admin authorisation.</label><label className="check"><input type="checkbox" name="enabled"/>Enable monitoring after saving</label><button>Save authorised monitor</button></form></section>
  <section className="panel"><div className="panel-head"><h2>Configured groups</h2><span>{operations.groups.length}</span></div><div className="table-wrap"><table><thead><tr><th>Group</th><th>Authorised</th><th>Enabled</th><th>Threshold</th><th>Categories</th><th>Quiet hours</th><th>Mode</th><th>Retention</th></tr></thead><tbody>{operations.groups.map(group=><tr key={group.groupId}><td>{group.title}<br/><small>{group.groupId}</small></td><td>{group.adminAuthorised?"Yes":"No"}</td><td>{group.enabled?"Yes":"No"}</td><td>{group.minimumScore}</td><td>{group.keywordCategories.length}</td><td>{group.quietHours?`${String(group.quietHours.startHour)}–${String(group.quietHours.endHour)}`:"Off"}</td><td>{group.responseMode}</td><td>{group.retentionDays} days</td></tr>)}</tbody></table></div></section></main>
}
