import { notFound, redirect } from "next/navigation";
import { currentAdmin, loadLead } from "../../../../lib/admin";
export const dynamic = "force-dynamic";
export default async function LeadPage({params}:{params:Promise<{id:string}>}){
  const admin=await currentAdmin();if(!admin)redirect("/admin/login");const {id}=await params;const lead=await loadLead(id);if(!lead)notFound();
  const q=lead.qualification;
  return <main className="admin-shell"><a href="/admin">← Dashboard</a><header className="admin-top"><div><span>LEAD DETAIL</span><h1>{lead.intake.name}</h1><p>{lead.status} · {lead.intakeKind} · {lead.attributionSource}</p></div></header>
  <section className="detail-grid"><article className="panel"><h2>Structured intake</h2><dl>{Object.entries(lead.intake).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{Array.isArray(value)?value.join(" · "):typeof value==="boolean"?(value?"Yes":"No"):String(value??"")}</dd></div>)}</dl></article>
  <article className="panel"><h2>Qualification</h2>{q?<><p><b>{q.recommendedPackage}</b> · {q.riskLevel} risk · {q.confidenceScore}% confidence</p><h3>Acceptance test</h3><ol>{q.proposedAcceptanceTest.map(item=><li key={item}>{item}</li>)}</ol><h3>Flags</h3><p>{q.manualReviewFlags.join(" · ")||"None"}</p></>:<p>Awaiting deterministic qualification.</p>}<h3>Attachments</h3>{lead.attachments.length?<ul>{lead.attachments.map(file=><li key={file.id}><a href={`/api/admin/attachments/${file.id}`}>{file.safeName}</a> · {Math.ceil(file.sizeBytes/1024)} KB · {file.scanStatus} · delete {new Date(file.deleteAfter).toLocaleDateString("en-GB")}</li>)}</ul>:<p className="muted">No attachments.</p>}<h3>Conversation</h3>{lead.conversation.length?<ol>{lead.conversation.map(message=><li key={message.id}><b>{message.direction}</b> · {new Date(message.createdAt).toLocaleString("en-GB")}<br/>{message.body}</li>)}</ol>:<p className="muted">No client replies yet.</p>}</article></section>
  <section className="detail-grid">{!lead.latestQuote?<form className="panel" method="post" action={`/api/admin/leads/${id}/quote`}><h2>Approve quote</h2><input type="hidden" name="csrf" value={admin.csrf}/><label>Scope<textarea name="scope" required defaultValue={q?.requestSummary}/></label><label>Acceptance test<textarea name="acceptanceTest" required defaultValue={q?.proposedAcceptanceTest.join("\n")}/></label><label>Price<input type="number" name="price" min="100" step="1" required defaultValue={q?.recommendedPrice.min??100}/></label><label>Network<select name="network"><option value="TRON_TRC20">USDT · TRON/TRC20</option><option value="BASE_USDC">Native USDC · Base</option></select></label><label>Quote validity in hours<input type="number" name="expiryHours" min="1" max="168" defaultValue="24" required/></label><label>Delivery window<input name="deliveryWindow" required defaultValue={q?.proposedDeliveryWindow??"After access is safely provided"}/></label><label>Included work<textarea name="includedWork" required defaultValue={q?.proposedAcceptanceTest.map(item=>`Implement and verify: ${item}`).join("\n")}/></label><label>Exclusions<textarea name="exclusions" defaultValue={q?.scopeExclusions.join("\n")}/></label><label>Refund terms<textarea name="refundTerms" required defaultValue="Refunds are manually reviewed against the approved scope and acceptance test. No automatic outgoing crypto transfer is performed."/></label><button>Approve quote</button></form>:<article className="panel"><h2>Approved quote</h2><p><b>{lead.latestQuote.currency} {Number(BigInt(lead.latestQuote.priceMinor))/1_000_000}</b> · {lead.latestQuote.network}</p><p>Expires {new Date(lead.latestQuote.expiresAt).toLocaleString("en-GB")}</p><p>{lead.latestQuote.scope}</p><h3>Included work</h3><ul>{lead.latestQuote.includedWork.map(item=><li key={item}>{item}</li>)}</ul><h3>Refund terms</h3><p>{lead.latestQuote.refundTerms}</p>{!lead.latestInvoice?<form method="post" action={`/api/admin/quotes/${lead.latestQuote.id}/invoice`}><input type="hidden" name="csrf" value={admin.csrf}/><input type="hidden" name="leadId" value={id}/><input type="hidden" name="network" value={lead.latestQuote.network}/><button>Generate capacity-checked invoice</button></form>:<p>Invoice: <b>{lead.latestInvoice.status}</b> · {lead.latestInvoice.id}</p>}{lead.job?<p><a className="primary-link" href={`/admin/jobs/${lead.job.id}`}>Open paid job card →</a></p>:null}</article>}
  <div className="panel"><h2>Private reply</h2><form method="post" action={`/api/admin/leads/${id}/messages`}><input type="hidden" name="csrf" value={admin.csrf}/><label>Message to client<textarea name="message" required minLength={1} maxLength={4000}/></label><button>Send through private Telegram notification</button></form>{lead.latestInvoice&&lead.latestInvoice.status!=="paid"?<form method="post" action={`/api/admin/invoices/${lead.latestInvoice.id}/manual-confirm`}><h3>Exceptional manual payment confirmation</h3><p className="alert">Use only after independently checking the chain, token, recipient, amount, confirmations, and transaction reuse. This does not send or refund crypto.</p><input type="hidden" name="csrf" value={admin.csrf}/><label>Transaction hash<input name="txHash" required pattern="(0x)?[0-9a-fA-F]{64}"/></label><label>Audit reason<textarea name="reason" required minLength={20} maxLength={2000}/></label><label className="check"><input type="checkbox" name="acknowledged" required/>I independently verified the payment evidence and accept responsibility for this override.</label><button className="danger">Record manual confirmation</button></form>:null}</div>
  <form className="panel" method="post" action={`/api/admin/leads/${id}/action`}><h2>Review action</h2><input type="hidden" name="csrf" value={admin.csrf}/><label>Action<select name="action"><option value="awaiting_information">Request information</option><option value="rejected">Reject</option><option value="rejected_unsafe">Mark unsafe</option></select></label><label>Client-safe reason<textarea name="reason" required maxLength={2000}/></label><button className="danger">Apply audited action</button></form></section></main>
}
