import { randomUUID } from "node:crypto";
import type { Intake } from "../../../packages/domain/src/index.ts";
export type WizardKind = "fix" | "agency" | "rescue";
export interface WizardSession { kind: WizardKind; step: number; answers: Record<string,string>; cancelled: boolean; completed: boolean; updatedAt: number; }
export interface WizardPrompt { field:string; prompt:string; required:boolean; }
const flows:Record<WizardKind,WizardPrompt[]>={
  fix:[
    {field:"name",prompt:"Your name?",required:true},{field:"company",prompt:"Company or project?",required:false},{field:"contact",prompt:"Contact email, or type Telegram",required:true},{field:"applicationUrl",prompt:"Application URL (stored only; never fetched automatically)",required:false},{field:"stack",prompt:"Technology stack?",required:true},{field:"environment",prompt:"Environment: local, staging, or production?",required:true},{field:"brokenBehaviour",prompt:"What exactly is broken?",required:true},{field:"expectedBehaviour",prompt:"What should happen?",required:true},{field:"reproductionSteps",prompt:"List the reproduction steps",required:true},{field:"errorMessage",prompt:"Paste the safe error message, without secrets",required:false},{field:"deadline",prompt:"Deadline?",required:false},{field:"budget",prompt:"Budget range?",required:false},{field:"ownershipConfirmed",prompt:"Confirm you own this project or have permission: yes/no",required:true},{field:"accessMethod",prompt:"Preferred safe access method?",required:true}
  ],
  agency:[
    {field:"agencyName",prompt:"Agency name?",required:true},{field:"contactRole",prompt:"Your role?",required:true},{field:"agencyWebsite",prompt:"Agency website?",required:false},{field:"endClientRequirement",prompt:"Describe the end-client requirement",required:true},{field:"approvedFunded",prompt:"Is the task approved and funded? yes/no",required:true},{field:"stack",prompt:"Technology stack?",required:true},{field:"deadline",prompt:"Deadline?",required:true},{field:"whiteLabel",prompt:"White-label required? yes/no",required:true},{field:"communication",prompt:"Communication arrangement?",required:true},{field:"budget",prompt:"Retail budget, if you choose to share it",required:false},{field:"acceptanceCriteria",prompt:"Acceptance criteria?",required:true},{field:"confidentiality",prompt:"Requested confidentiality level?",required:true},{field:"ownershipConfirmed",prompt:"Confirm the agency is authorised to commission this work: yes/no",required:true}
  ],
  rescue:[
    {field:"name",prompt:"Your name and company?",required:true},{field:"businessImpact",prompt:"What is the business impact?",required:true},{field:"productionStatus",prompt:"Current production status?",required:true},{field:"recentChange",prompt:"What changed recently?",required:false},{field:"usersAffected",prompt:"How many users are affected?",required:false},{field:"errors",prompt:"Current safe error details?",required:true},{field:"tests",prompt:"What tests currently exist?",required:false},{field:"repository",prompt:"Repository size and stack?",required:true},{field:"deploymentProvider",prompt:"Deployment provider?",required:true},{field:"database",prompt:"Database?",required:false},{field:"urgency",prompt:"Urgency?",required:true},{field:"rollback",prompt:"Is a safe rollback available? yes/no",required:true},{field:"requiredAccess",prompt:"Required access?",required:true},{field:"ownershipConfirmed",prompt:"Confirm ownership or written permission: yes/no",required:true}
  ]
};
export function startWizard(kind:WizardKind,now=Date.now()):WizardSession{return{kind,step:0,answers:{},cancelled:false,completed:false,updatedAt:now}}
export function currentPrompt(s:WizardSession){return flows[s.kind][s.step]}
export function answerWizard(s:WizardSession,input:string,now=Date.now()):{session:WizardSession;error?:string;next?:WizardPrompt}{
  if(s.cancelled)return{session:s,error:"SESSION_CANCELLED"}; if(s.completed)return{session:s,error:"SESSION_COMPLETED"}; const p=currentPrompt(s); if(!p)return{session:{...s,completed:true,updatedAt:now}};
  const value=input.trim(); if(p.required&&!value)return{session:s,error:"REQUIRED_FIELD",next:p}; if(/password\s*=|seed phrase|private key|\.env\b/i.test(value))return{session:s,error:"POTENTIAL_SECRET",next:p};
  const answers={...s.answers,[p.field]:value}; const step=s.step+1; const completed=step>=flows[s.kind].length; const session={...s,answers,step,completed,updatedAt:now}; return{session,...(!completed?{next:flows[s.kind][step]}:{})};
}
export function cancelWizard(s:WizardSession,now=Date.now()){return{...s,cancelled:true,updatedAt:now}}
export function resumeWizard(s:WizardSession,maxIdleMs=7*24*3600_000,now=Date.now()){if(now-s.updatedAt>maxIdleMs)return{ok:false as const,reason:"SESSION_EXPIRED"};if(s.cancelled)return{ok:false as const,reason:"SESSION_CANCELLED"};return{ok:true as const,session:s,prompt:currentPrompt(s)}}
export function flowLength(kind:WizardKind){return flows[kind].length}

function yes(value:string|undefined){return /^(yes|y|true|confirmed)$/i.test(value?.trim()??"")}
function lines(value:string|undefined){return(value??"").split(/\n|;/).map(item=>item.trim()).filter(Boolean).slice(0,30)}
function environment(value:string|undefined):"local"|"staging"|"production"{const x=value?.toLowerCase();return x==="local"||x==="production"?x:"staging"}
export function wizardToIntake(session:WizardSession,id:string=randomUUID()):Intake{
  if(!session.completed||session.cancelled)throw new Error("WIZARD_NOT_COMPLETE");const a=session.answers;
  if(session.kind==="fix")return{id,kind:"quick-fix",name:a.name??"Telegram client",...(a.company?{company:a.company}:{}),...(a.contact?{contactPreference:a.contact}:{}),...(a.applicationUrl?{applicationUrl:a.applicationUrl}:{}),...(a.accessMethod?{accessMethodPreference:a.accessMethod}:{}),stack:lines(a.stack),environment:environment(a.environment),brokenBehaviour:a.brokenBehaviour??"",expectedBehaviour:a.expectedBehaviour??"",reproductionSteps:lines(a.reproductionSteps),...(a.errorMessage?{errorMessage:a.errorMessage}:{}),...(a.deadline?{deadline:a.deadline}:{}),...(a.budget?{budget:a.budget}:{}),ownershipConfirmed:yes(a.ownershipConfirmed),requiredAccessAvailable:Boolean(a.accessMethod),estimatedMinutes:90};
  if(session.kind==="agency")return{id,kind:"agency-overflow",name:a.contactRole??"Agency contact",company:a.agencyName??"Agency",...(a.contactRole?{contactRole:a.contactRole}:{}),...(a.agencyWebsite?{agencyWebsite:a.agencyWebsite}:{}),...(a.endClientRequirement?{endClientRequirement:a.endClientRequirement}:{}),whiteLabelRequired:yes(a.whiteLabel),...(a.communication?{communicationArrangement:a.communication}:{}),...(a.confidentiality?{confidentialityLevel:a.confidentiality}:{}),stack:lines(a.stack),environment:"staging",brokenBehaviour:a.endClientRequirement??"",expectedBehaviour:a.acceptanceCriteria??"",reproductionSteps:lines(a.acceptanceCriteria),...(a.deadline?{deadline:a.deadline}:{}),...(a.budget?{budget:a.budget}:{}),ownershipConfirmed:yes(a.ownershipConfirmed),approvedAndFunded:yes(a.approvedFunded),requiredAccessAvailable:true,acceptanceCriteria:lines(a.acceptanceCriteria),estimatedMinutes:240};
  const affected=Number.parseInt(a.usersAffected??"",10);return{id,kind:"production-rescue",name:a.name??"Telegram client",...(a.businessImpact?{businessImpact:a.businessImpact}:{}),...(a.productionStatus?{productionStatus:a.productionStatus}:{}),existingTests:lines(a.tests),...(a.repository?{repositoryDescription:a.repository}:{}),...(a.deploymentProvider?{deploymentProvider:a.deploymentProvider}:{}),...(a.database?{database:a.database}:{}),...(a.urgency?{urgency:a.urgency}:{}),...(a.requiredAccess?{requiredAccess:a.requiredAccess}:{}),stack:lines(a.repository),environment:"production",brokenBehaviour:[a.businessImpact,a.errors].filter(Boolean).join(" — "),expectedBehaviour:"Restore the affected production workflow and prove the agreed acceptance checks.",reproductionSteps:lines(a.recentChange||a.errors),ownershipConfirmed:yes(a.ownershipConfirmed),productionDown:/down|offline|unavailable|outage/i.test(a.productionStatus??""),...(Number.isFinite(affected)?{usersAffected:affected}:{}),...(a.recentChange?{recentChange:a.recentChange}:{}),safeRollbackAvailable:yes(a.rollback),requiredAccessAvailable:Boolean(a.requiredAccess),estimatedMinutes:360};
}
