import { NextResponse } from "next/server";
import { createPostgresRepository } from "@jawad/database";
import { sameOrigin,verifyAdminSession,verifyCsrfToken } from "@jawad/security";
function cookie(request:Request,name:string){return request.headers.get("cookie")?.match(new RegExp(`(?:^|; )${name}=([^;]+)`))?.[1]}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!sameOrigin(request.url,request.headers.get("origin")))return NextResponse.json({error:"ORIGIN_REJECTED"},{status:403});
  const secret=process.env.ADMIN_SESSION_SECRET??"";const sessionToken=cookie(request,"jawad_admin_session");const session=verifyAdminSession(sessionToken,secret);const form=await request.formData();const csrf=String(form.get("csrf")??"");if(!session||session.role!=="owner"||csrf!==cookie(request,"jawad_csrf")||!verifyCsrfToken(sessionToken??"",csrf,secret))return NextResponse.json({error:"AUTH_REJECTED"},{status:403});
  const price=Number(form.get("price"));const network=String(form.get("network"));const expiryHours=Number(form.get("expiryHours"));if(!Number.isFinite(price)||price<100||price>1_000_000||!["TRON_TRC20","BASE_USDC"].includes(network)||!Number.isInteger(expiryHours)||expiryHours<1||expiryHours>168)return NextResponse.json({error:"INVALID_QUOTE"},{status:422});const {id}=await params;
  if(process.env.NODE_ENV!=="production"&&(process.env.DEMO_MODE??"true")==="true")return NextResponse.redirect(new URL(`/admin/leads/${id}`,request.url),303);if(!process.env.DATABASE_URL||!process.env.DATA_ENCRYPTION_KEY)return NextResponse.json({error:"DATABASE_NOT_CONFIGURED"},{status:503});
  const repo=await createPostgresRepository(process.env.DATABASE_URL,process.env.DATA_ENCRYPTION_KEY);try{const quoteId=await repo.createApprovedQuote({leadId:id,scope:String(form.get("scope")??"").slice(0,8000),acceptanceTest:String(form.get("acceptanceTest")??"").split("\n").map(v=>v.trim()).filter(Boolean).slice(0,30),priceMinor:BigInt(Math.round(price*1_000_000)),currency:network==="TRON_TRC20"?"USDT":"USDC",network:network as "TRON_TRC20"|"BASE_USDC",deliveryWindow:String(form.get("deliveryWindow")??"").slice(0,500),exclusions:String(form.get("exclusions")??"").split("\n").map(v=>v.trim()).filter(Boolean).slice(0,30),includedWork:String(form.get("includedWork")??"").split("\n").map(v=>v.trim()).filter(Boolean).slice(0,30),refundTerms:String(form.get("refundTerms")??"").trim().slice(0,2000)||"Refunds are manually reviewed against the approved scope and acceptance test. No automatic outgoing crypto transfer is performed.",expiresAt:new Date(Date.now()+expiryHours*60*60_000),approvedBy:session.subject});const target=await repo.getLeadTelegramTarget(id);if(target)await repo.queueNotification({kind:"Quote approved",recipientChatId:target.telegramUserId,leadId:id,payload:{text:`Your Jawad Dev Desk quote is ready. Ticket ${target.ticketId}. Review the scope, acceptance test, price, expiry, and exclusions in the Mini App. Quote reference: ${quoteId}. No payment is requested until an invoice appears.`}});return NextResponse.redirect(new URL(`/admin/leads/${id}`,request.url),303)}finally{await repo.close()}
}
