"use client";

import { useEffect, useMemo, useState } from "react";

const sections = ["home","services","portfolio","submit","current","quote","invoice","payment","status","delivery","referral","privacy"] as const;
type Section = typeof sections[number];
const sectionCopy: Record<Section,{title:string;body:string}> = {
  home:{title:"Jawad Dev Desk",body:"Production rescue and white-label engineering with structured intake, human approval, and on-chain payment evidence."},
  services:{title:"Supported work",body:"React/Next.js, Node.js, Python/FastAPI, PostgreSQL, authentication, dashboards, integrations, Docker, deployment, responsiveness, and existing-feature repair."},
  portfolio:{title:"Proof of work",body:"Review the public portfolio, GitHub profile, GoPilot Express case study, and LOOSH production work. Confidential client data is never displayed."},
  submit:{title:"Submit a task",body:"Describe one reproducible requirement. Never upload credentials, .env files, private keys, seed phrases, or production database dumps."},
  current:{title:"Current submission",body:"Resume a saved ticket reference and review its current manual-review state."},
  quote:{title:"Quote",body:"Scope, acceptance test, price, delivery window, exclusions, and expiry appear only after Jawad approves them."},
  invoice:{title:"Crypto invoice",body:"Supported networks are USDT on TRON/TRC20 and native USDC on Base. Verify the network label and address before paying."},
  payment:{title:"Payment verification",body:"Submit a transaction hash. Chain data is read only, revalidated in the database, and ambiguous transfers are never auto-assigned."},
  status:{title:"Job status",body:"Track the private ticket without exposing project details in public chats."},
  delivery:{title:"Delivery",body:"Review the engineering summary, proof, test results, and objective acceptance checklist."},
  referral:{title:"Testimonial & referral",body:"After successful acceptance, share an optional testimonial or referral. Partner payouts remain manually approved."},
  privacy:{title:"Privacy",body:"Uploads are restricted, scanned when available, stored outside the public root, and deleted under the configured retention policy."},
};
function telegramInitData():string{return typeof window==="undefined"?"":(window as any).Telegram?.WebApp?.initData??""}
function telegramHeaders():Record<string,string>{return{"x-telegram-init-data":telegramInitData()}}
function openExternal(url:string){const webApp=(window as any).Telegram?.WebApp;if(typeof webApp?.openLink==="function")webApp.openLink(url);else window.open(url,"_blank","noopener,noreferrer")}
function tokenAmount(minor:string,decimals:number){const raw=minor.padStart(decimals+1,"0");return`${raw.slice(0,-decimals)}.${raw.slice(-decimals)}`.replace(/\.0+$/,"")}

export function MiniAppShell({section="home"}:{section?:string}){
  const active=sections.includes(section as Section)?section as Section:"home";
  const [theme,setTheme]=useState("dark");const [result,setResult]=useState("");const [submitting,setSubmitting]=useState(false);const [ticket,setTicket]=useState<any>(null);const [invoice,setInvoice]=useState<any>(null);const content=useMemo(()=>sectionCopy[active],[active]);
  useEffect(()=>{const webApp=(window as any).Telegram?.WebApp;webApp?.ready?.();webApp?.expand?.();setTheme(webApp?.colorScheme??"dark");const params=webApp?.themeParams??{};if(params.bg_color)document.documentElement.style.setProperty("--tg-bg",params.bg_color);if(params.text_color)document.documentElement.style.setProperty("--tg-text",params.text_color);if(params.button_color)document.documentElement.style.setProperty("--tg-button",params.button_color);const start=String(webApp?.initDataUnsafe?.start_param??"");if(start.startsWith("partner_"))sessionStorage.setItem("jawad_referral_slug",start.slice(8));const saved=sessionStorage.getItem("jawad_ticket_id");if(saved)setResult(`Saved ticket: ${saved}`)},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);const body={id:crypto.randomUUID(),kind:String(form.get("kind")??"quick-fix"),name:String(form.get("name")??""),company:String(form.get("company")??""),stack:String(form.get("stack")??"").split(",").map(v=>v.trim()).filter(Boolean),environment:String(form.get("environment")??"staging"),brokenBehaviour:String(form.get("brokenBehaviour")??""),expectedBehaviour:String(form.get("expectedBehaviour")??""),reproductionSteps:String(form.get("reproductionSteps")??"").split("\n").map(v=>v.trim()).filter(Boolean),ownershipConfirmed:form.get("ownershipConfirmed")==="on",requiredAccessAvailable:form.get("requiredAccessAvailable")==="on",estimatedMinutes:Number(form.get("estimatedMinutes")??90),referralSlug:sessionStorage.getItem("jawad_referral_slug")||undefined};try{const response=await fetch("/api/intake",{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify(body)});const data=await response.json();if(response.ok){sessionStorage.setItem("jawad_ticket_id",data.id);let message=`Submitted safely. Ticket: ${data.id}. ${data.qualification.recommendedPackage} is a recommendation only; Jawad must approve the quote.`;const attachment=form.get("attachment");if(attachment instanceof File&&attachment.size>0){const upload=new FormData();upload.set("leadId",data.id);upload.set("file",attachment);const uploadResponse=await fetch("/api/attachments",{method:"POST",headers:telegramHeaders(),body:upload});const uploadData=await uploadResponse.json();message+=uploadResponse.ok?` Attachment ${uploadData.safeName} stored with ${uploadData.scanStatus} scan status.`:` Attachment was not stored: ${uploadData.error??"REJECTED"}.`}setResult(message)}else setResult(`Submission failed: ${data.error??"UNKNOWN"}`)}catch{setResult("Submission failed safely. Check your connection and retry.")}finally{setSubmitting(false)}}
  async function loadTicket(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const id=String(new FormData(event.currentTarget).get("ticketId")??"").trim();try{const response=await fetch(`/api/tickets/${encodeURIComponent(id)}`,{headers:telegramHeaders()});const data=await response.json();if(!response.ok)throw new Error(data.error??"TICKET_LOOKUP_FAILED");setTicket(data);sessionStorage.setItem("jawad_ticket_id",id);if(data.invoice)setInvoice(data.invoice);setResult(`Ticket ${id} loaded safely.`)}catch(error){setResult(error instanceof Error?error.message:"TICKET_LOOKUP_FAILED")}finally{setSubmitting(false)}}
  async function loadInvoice(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const id=String(new FormData(event.currentTarget).get("invoiceId")??"").trim();try{const response=await fetch(`/api/invoices/${encodeURIComponent(id)}`,{headers:telegramHeaders()});const data=await response.json();if(!response.ok)throw new Error(data.error??"INVOICE_LOOKUP_FAILED");setInvoice(data);setResult(data.demo?"Demo invoice loaded. Do not send funds to demo values.":"Invoice loaded. Recheck network and recipient before paying.")}catch(error){setResult(error instanceof Error?error.message:"INVOICE_LOOKUP_FAILED")}finally{setSubmitting(false)}}
  async function verifyPayment(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);const invoiceId=String(form.get("invoiceId")??invoice?.id??"").trim();const txHash=String(form.get("txHash")??"").trim();try{const response=await fetch(`/api/invoices/${encodeURIComponent(invoiceId)}/verify`,{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify({txHash})});const data=await response.json();if(!response.ok)throw new Error(data.error??"PAYMENT_VERIFICATION_FAILED");setResult(`Payment status: ${data.code}. Job: ${data.jobId}.`)}catch(error){setResult(error instanceof Error?error.message:"PAYMENT_VERIFICATION_FAILED")}finally{setSubmitting(false)}}
  async function requestDeletion(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/privacy/deletion",{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify({email:String(form.get("email")??""),notes:String(form.get("notes")??"")})});const data=await response.json();if(!response.ok)throw new Error(data.error??"DELETION_REQUEST_FAILED");setResult(`Deletion request ${data.id} is open for identity verification and manual processing.`)}catch(error){setResult(error instanceof Error?error.message:"DELETION_REQUEST_FAILED")}finally{setSubmitting(false)}}
  async function submitTestimonial(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/testimonials",{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify({jobId:String(form.get("jobId")??ticket?.job?.id??""),response:String(form.get("response")??""),permissionToPublish:form.get("permissionToPublish")==="on"})});const data=await response.json();if(!response.ok)throw new Error(data.error??"TESTIMONIAL_FAILED");setResult(`Testimonial ${data.id} received. Publication permission remains ${form.get("permissionToPublish")==="on"?"granted":"not granted"}.`)}catch(error){setResult(error instanceof Error?error.message:"TESTIMONIAL_FAILED")}finally{setSubmitting(false)}}
  async function sendClientMessage(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);const ticketId=String(form.get("ticketId")??ticket?.id??"").trim();const message=String(form.get("message")??"").trim();try{const response=await fetch(`/api/tickets/${encodeURIComponent(ticketId)}/messages`,{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify({body:message})});const data=await response.json();if(!response.ok)throw new Error(data.error??"CLIENT_MESSAGE_FAILED");setResult(`Message ${data.id} was delivered to the private ticket history.`);event.currentTarget.reset();await refreshTicket(ticketId)}catch(error){setResult(error instanceof Error?error.message:"CLIENT_MESSAGE_FAILED")}finally{setSubmitting(false)}}
  async function acceptDelivery(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setResult("");const form=new FormData(event.currentTarget);const jobId=String(form.get("jobId")??ticket?.job?.id??"").trim();const feedback=String(form.get("feedback")??"").trim();try{const response=await fetch(`/api/jobs/${encodeURIComponent(jobId)}/accept`,{method:"POST",headers:{"content-type":"application/json",...telegramHeaders()},body:JSON.stringify({feedback})});const data=await response.json();if(!response.ok)throw new Error(data.error??"DELIVERY_ACCEPTANCE_FAILED");setResult(`Delivery accepted. Ticket ${data.ticketId} is complete.`);const ticketId=String(ticket?.id??"");if(ticketId)await refreshTicket(ticketId)}catch(error){setResult(error instanceof Error?error.message:"DELIVERY_ACCEPTANCE_FAILED")}finally{setSubmitting(false)}}
  async function refreshTicket(id:string){if(!id)return;const response=await fetch(`/api/tickets/${encodeURIComponent(id)}`,{headers:telegramHeaders()});if(!response.ok)return;const data=await response.json();setTicket(data);if(data.invoice)setInvoice(data.invoice)}
  async function downloadProof(id:string,safeName:string){setSubmitting(true);setResult("");try{const response=await fetch(`/api/client/attachments/${encodeURIComponent(id)}`,{headers:telegramHeaders()});if(!response.ok)throw new Error(await response.text()||"PROOF_DOWNLOAD_FAILED");const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=safeName||"proof.bin";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setResult(`Proof ${safeName} downloaded securely.`)}catch(error){setResult(error instanceof Error?error.message:"PROOF_DOWNLOAD_FAILED")}finally{setSubmitting(false)}}
  async function openPrivateAsset(path:string,filename?:string){setSubmitting(true);setResult("");try{const response=await fetch(path,{headers:telegramHeaders()});if(!response.ok)throw new Error(await response.text()||"PRIVATE_ASSET_FAILED");const blob=await response.blob();const url=URL.createObjectURL(blob);if(filename){const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove()}else window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),30_000)}catch(error){setResult(error instanceof Error?error.message:"PRIVATE_ASSET_FAILED")}finally{setSubmitting(false)}}
  const savedTicket=typeof window!=="undefined"?sessionStorage.getItem("jawad_ticket_id")??"":"";
  const ticketLookup=<form className="intake-form compact" onSubmit={loadTicket}><label>Private ticket reference<input name="ticketId" required defaultValue={savedTicket}/></label><button disabled={submitting}>Load ticket</button></form>;
  return <main className="mini-app" data-theme={theme}><header className="mini-header"><span>JAWAD DEV DESK</span><h1>{content.title}</h1><p>{content.body}</p></header><nav className="mini-nav" aria-label="Mini App pages">{sections.map(item=><a key={item} className={item===active?"active":""} href={`/mini-app/${item}`}>{item.replaceAll("-"," ")}</a>)}</nav>
    {active==="submit"?<form className="intake-form" onSubmit={submit}><label>Request type<select name="kind"><option value="quick-fix">Fix a Bug</option><option value="agency-overflow">Agency Overflow</option><option value="production-rescue">Production Rescue</option></select></label><label>Name<input name="name" required maxLength={100}/></label><label>Company/project<input name="company" maxLength={120}/></label><label>Stack, comma separated<input name="stack" required placeholder="Next.js, Node.js, PostgreSQL" maxLength={240}/></label><label>Environment<select name="environment"><option>local</option><option>staging</option><option>production</option></select></label><label>Exact broken behaviour<textarea name="brokenBehaviour" required maxLength={4000}/></label><label>Expected behaviour<textarea name="expectedBehaviour" required maxLength={4000}/></label><label>Reproduction steps, one per line<textarea name="reproductionSteps" required maxLength={4000}/></label><label>Safe attachment (PNG, JPG, WebP, TXT, LOG, PDF, ZIP; max 10 MB)<input name="attachment" type="file" accept=".png,.jpg,.jpeg,.webp,.txt,.log,.pdf,.zip"/></label><label>Estimated minutes<input name="estimatedMinutes" type="number" min="15" max="10000" defaultValue="90"/></label><label className="check"><input name="ownershipConfirmed" type="checkbox" required/>I own this project or have written permission.</label><label className="check"><input name="requiredAccessAvailable" type="checkbox"/>Required safe access can be provided after approval.</label><button disabled={submitting}>{submitting?"Submitting…":"Submit for manual review"}</button></form>:null}
    {["current","quote","status","delivery"].includes(active)?<section className="mini-card">{ticketLookup}{ticket?<div className="ticket-view"><h2>Status: {ticket.status}</h2><p>Created {new Date(ticket.createdAt).toLocaleString("en-GB")}</p>{ticket.quote?<><h3>Approved quote</h3><p>{ticket.quote.scope}</p><p><b>{ticket.quote.currency} {tokenAmount(ticket.quote.priceMinor,6)}</b> · {ticket.quote.network}</p><ol>{ticket.quote.acceptanceTest.map((item:string)=><li key={item}>{item}</li>)}</ol>{ticket.quote.includedWork?.length?<><h4>Included work</h4><ul>{ticket.quote.includedWork.map((item:string)=><li key={item}>{item}</li>)}</ul></>:null}<h4>Refund terms</h4><p>{ticket.quote.refundTerms??"Manual review only; no automatic refund."}</p></>:<p>No approved quote yet.</p>}{ticket.invoice?<p>Invoice: {ticket.invoice.status} · {ticket.invoice.id}</p>:null}{ticket.job?<><h3>Job card</h3><p>{ticket.job.status}</p><p>{ticket.job.deliveryMessage??"Delivery has not been posted yet."}</p>{ticket.job.testResults?.length?<><h4>Test results</h4><ul>{ticket.job.testResults.map((item:string)=><li key={item}>{item}</li>)}</ul></>:null}{ticket.job.attachments?.length?<><h4>Proof attachments</h4><ul>{ticket.job.attachments.map((item:any)=><li key={item.id}><button type="button" disabled={submitting} onClick={()=>downloadProof(item.id,item.safeName)}>{item.safeName}</button> · {Math.ceil(item.sizeBytes/1024)} KB</li>)}</ul></>:null}</>:null}{ticket.conversation?.length?<><h3>Private history</h3><ol>{ticket.conversation.map((item:any)=><li key={item.id}><b>{item.direction}</b> · {new Date(item.createdAt).toLocaleString("en-GB")}<br/>{item.body}</li>)}</ol></>:null}{["current","status"].includes(active)?<form className="intake-form compact" onSubmit={sendClientMessage}><input type="hidden" name="ticketId" value={ticket.id}/><label>Private reply<textarea name="message" required minLength={2} maxLength={4000}/></label><button disabled={submitting}>Send private reply</button></form>:null}{active==="delivery"&&ticket.job?.status==="awaiting_client_acceptance"?<form className="intake-form compact" onSubmit={acceptDelivery}><input type="hidden" name="jobId" value={ticket.job.id}/><label>Acceptance feedback, optional<textarea name="feedback" maxLength={2000}/></label><label className="check"><input type="checkbox" required/>I reviewed the delivery summary, proof, tests, and acceptance checklist.</label><button disabled={submitting}>Accept delivery</button></form>:null}{active==="delivery"&&ticket.job?.status==="completed"?<p><a className="primary-link" href="/mini-app/referral">Share an optional testimonial or referral</a></p>:null}</div>:null}</section>:null}
    {active==="invoice"?<section className="mini-card"><form className="intake-form compact" onSubmit={loadInvoice}><label>Invoice reference<input name="invoiceId" required defaultValue={ticket?.invoice?.id??""}/></label><button disabled={submitting}>Load invoice</button></form>{invoice?<div className="ticket-view"><h2>{invoice.token} · {invoice.network}</h2><p><b>{tokenAmount(invoice.amountMinor,invoice.decimals)}</b></p><p className="break-all">Recipient: {invoice.recipientAddress}</p><p>Expires {new Date(invoice.expiresAt).toLocaleString("en-GB")}</p><div className="invoice-actions"><button type="button" disabled={submitting} onClick={()=>openPrivateAsset(`/api/invoices/${encodeURIComponent(invoice.id)}/qr`,`invoice-${invoice.id}-qr.png`)}>Download payment QR</button><button type="button" disabled={submitting} onClick={()=>openPrivateAsset(`/api/invoices/${encodeURIComponent(invoice.id)}/receipt`)}>Open printable receipt</button></div>{invoice.demo?<p className="alert">Demo values are never payable.</p>:null}</div>:null}</section>:null}
    {active==="payment"?<section className="mini-card"><form className="intake-form compact" onSubmit={verifyPayment}><label>Invoice reference<input name="invoiceId" required defaultValue={invoice?.id??ticket?.invoice?.id??""}/></label><label>Transaction hash<input name="txHash" required pattern="(0x)?[0-9a-fA-F]{64}"/></label><button disabled={submitting}>Verify read-only on chain</button></form><p>No private key, signing request, refund, or outgoing transfer is handled here.</p></section>:null}
    {["home","services","portfolio"].includes(active)?<section className="mini-card"><h2>Manual control remains mandatory</h2><p>No request is automatically accepted, no invoice is created before approval, and no outgoing crypto action is performed by this system.</p>{active==="portfolio"?<p><button type="button" className="primary-link" onClick={()=>openExternal("https://mjszeineddine.github.io/")}>Open portfolio</button></p>:<a className="primary-link" href="/mini-app/submit">Start a safe submission</a>}</section>:null}
    {active==="referral"?<section className="mini-card">{ticketLookup}<form className="intake-form compact" onSubmit={submitTestimonial}><label>Completed job reference<input name="jobId" required defaultValue={ticket?.job?.id??""}/></label><label>Optional testimonial<textarea name="response" required minLength={10} maxLength={4000}/></label><label className="check"><input name="permissionToPublish" type="checkbox"/>Jawad may publish this testimonial with no confidential project information.</label><button disabled={submitting}>Submit testimonial</button></form><p>Referral commissions are recorded only for valid partner attribution, become eligible after accepted delivery, and are paid manually.</p></section>:null}
    {active==="privacy"?<section className="mini-card"><h2>Privacy controls</h2><p>Request deletion of your intake, attachments, and related personal data. Accounting and security records may be retained only where legally or operationally required.</p><form className="intake-form compact" onSubmit={requestDeletion}><label>Contact email, optional<input name="email" type="email" maxLength={200}/></label><label>Deletion notes, optional<textarea name="notes" maxLength={1000}/></label><button disabled={submitting}>Open deletion request</button></form></section>:null}
    {result?<output className="mini-output" aria-live="polite">{result}</output>:null}
  </main>;
}
