import { stat, readFile } from "node:fs/promises";
import { join } from "node:path";
const root=new URL("..",import.meta.url).pathname;
const required=["README.md","Dockerfile",".dockerignore","docker-compose.yml",".env.example","docs/capability-audit.md","docs/telegram-account-setup.md","docs/botfather-setup.md","docs/threat-model.md","docs/data-retention.md","docs/incident-response.md","docs/deployment.md","docs/rollback.md","docs/operations-runbook.md","docs/testing.md","content/channel-launch-posts.md","content/partner-offer.md","content/admin-partnership-message.md","content/pinned-group-post.md","content/referral-terms.md","PRIVACY.md","SECURITY.md","packages/database/migrations/001_initial.sql","packages/database/migrations/002_security.sql","packages/database/migrations/003_operations.sql","packages/database/migrations/004_reliability.sql","packages/database/migrations/005_monitor_controls.sql","packages/database/migrations/006_quote_delivery_fields.sql","packages/database/migrations/007_group_monitor_categories.sql","packages/database/migrations/008_job_operations.sql","packages/database/migrations/009_partner_operations.sql","packages/database/migrations/010_partner_fraud_controls.sql","tests/e2e/full-flow.ts","tests/integration/postgres-repository.test.ts","tests/browser/mobile.spec.ts","scripts/backup-database.ts","scripts/restore-test.ts","apps/bot/src/session-store.ts","screenshots/dashboard-desktop.svg","screenshots/mini-app-mobile.svg"];
for(const file of required)await stat(join(root,file));
const env=await readFile(join(root,".env.example"),"utf8");if(/RECEIVING_ADDRESS=\S+/.test(env))throw new Error("Wallet address must not be committed");
for(const key of ["TELEGRAM_BOT_TOKEN=","TELEGRAM_WEBHOOK_SECRET=","USDT_TRC20_RECEIVING_ADDRESS=","USDC_BASE_RECEIVING_ADDRESS=","BASE_RPC_URL="])if(!env.includes(key))throw new Error(`Missing environment key ${key}`);
const css=await readFile(join(root,"apps/demo/public/styles.css"),"utf8");if(!css.includes("minmax(0,1fr)")||!css.includes("@media"))throw new Error("Mobile layout safeguards missing");
const compose=await readFile(join(root,"docker-compose.yml"),"utf8");for(const value of ["postgres:","redis:","migrate:","web:","bot:","worker:","service_completed_successfully","uploads_data:/app/runtime/uploads","healthcheck:","restart: unless-stopped"])if(!compose.includes(value))throw new Error(`Compose missing ${value}`);
const mini=await readFile(join(root,"apps/web/components/MiniAppShell.tsx"),"utf8");for(const page of ["home","services","portfolio","submit","current","quote","invoice","payment","status","delivery","referral","privacy"])if(!mini.includes(`\"${page}\"`))throw new Error(`Mini App page missing: ${page}`);
const admin=await readFile(join(root,"apps/web/app/api/admin/login/route.ts"),"utf8");for(const control of ["sameOrigin","createAdminSession","createCsrfToken","httpOnly","sameSite"])if(!admin.includes(control))throw new Error(`Admin auth control missing: ${control}`);
const database=await readFile(join(root,"packages/database/src/index.ts"),"utf8");for(const control of ["getCapacitySettings","getGroupMonitor","queueNotification","submitTestimonial","createDeletionRequest","getAttachmentForAdmin","getAttachmentForClient","addAdminMessage","listPartnerStats","manualConfirmPayment","completeDeletionRequest","claimTelegramUpdate"])if(!database.includes(control))throw new Error(`Database operation missing: ${control}`);
const bot=await readFile(join(root,"apps/bot/src/grammy-adapter.ts"),"utf8");for(const control of ["loadGroupMonitor","onDemandSignal","demandAlertDecision","approvedTemplate"])if(!bot.includes(control))throw new Error(`Bot monitoring control missing: ${control}`);
const worker=await readFile(join(root,"apps/worker/src/bullmq-adapter.ts"),"utf8");for(const control of ["runQueuedNotifications","resolveWatcherAssignments","RETENTION_DELETE","markNotificationFailed"])if(!worker.includes(control))throw new Error(`Worker control missing: ${control}`);
for(const route of ["apps/web/app/admin/partners/page.tsx","apps/web/app/admin/privacy/page.tsx","apps/web/app/api/admin/invoices/[id]/manual-confirm/route.ts","apps/web/app/api/admin/jobs/[id]/details/route.ts","apps/web/app/api/admin/partners/route.ts","apps/web/app/api/admin/privacy/deletions/[id]/complete/route.ts","apps/web/app/api/admin/referrals/[id]/payout/route.ts","apps/web/app/api/invoices/[id]/qr/route.ts","apps/web/app/api/invoices/[id]/receipt/route.ts","apps/web/app/api/client/attachments/[id]/route.ts","apps/web/app/api/admin/leads/[id]/messages/route.ts","apps/web/app/api/jobs/[id]/accept/route.ts","apps/web/app/api/tickets/[id]/messages/route.ts","apps/web/app/api/privacy/deletion/route.ts","apps/web/app/api/testimonials/route.ts","apps/web/app/api/admin/attachments/[id]/route.ts","apps/web/app/api/admin/settings/capacity/route.ts","apps/web/app/api/admin/settings/groups/route.ts"])await stat(join(root,route));
for(const image of ["dashboard-desktop.svg","mini-app-mobile.svg"]){const svg=await readFile(join(root,"screenshots",image),"utf8");if(!svg.startsWith("<svg")||!/<svg[^>]+width="\d+"[^>]+height="\d+"/.test(svg))throw new Error(`${image} is not a valid sized SVG screenshot`)}
console.log("Validation PASS: repository, security, Mini App, admin controls, payments, partners, privacy deletion, durable bot state, backup tooling, screenshots, Docker definition");
